### ISSUE TITLE
Rename disablePictureInPicture to pictureInPictureDisabled

### ISSUE THREAD

**Issue by a2sheppy** [w3c/picture-in-picture#160]
HTML tends to use the past-tense verb "disabled" in names for Boolean attributes (such as `<input>`'s `disabled` attribute), rather than the imperative "disable". Consider renaming `disablePictureInPicture` to `pictureInPictureDisabled` to align with this.

**Comment by beaufortfrancois** [comment]
Looking at https://cs.chromium.org/search/?q=f:expected+f:global+f:txt+f:webexposed+%22setter+disable%22+f:stable&sq=package:chromium&type=cs, it seems like `disabled` was used to disable the HTML element completely. I can't find an attribute that ends with "disabled".

For info, we've picked `disablePictureInPicture` because of a similar `disableRemotePlayback` attribute.

WDYT @mounirlamouri?

**Comment by mounirlamouri** [comment]
I wouldn't mind much between one or the other if we didn't already ship in
Chrome. With one implementation out there, and with remote playback
precedent, it seems worth keeping the current name IMO.

**Comment by a2sheppy** [comment]
You're right then. Leave it as is. I say to drop this.
