### ISSUE TITLE
don't allow pages to disable PiP without a user gesture

### ISSUE THREAD

**Issue by Poopooracoocoo** [w3c/picture-in-picture#178]
I strongly believe that it should be up to users to use PiP if they want to. Making it easy is one thing, blocking it altogether is another. When users install extensions like Google's PiP, they expect it to always work. This may just be an issue of the Google's PiP extension for Chrome though. I can't think of any use cases for websites being able to disable PiP without a user gesture. Maybe that's already not possible and perhaps some pages just exit PiP when they know that a video has entered PiP mode. Please correct me.

**Comment by alectrocute** [comment]
Highly disagree * 100, sorry.

Think of the world of Electron apps that depend on Picture-in-Picture opening automatically upon a screencast, etc.

**Comment by beaufortfrancois** [comment]
We believe it should be up to the website to decide if a Picture-in-Picture mode is desirable. For this, the spec has added the `disablePictureInPicture` HTMLVideoElement attribute and the `picture-in-picture` feature policy.

https://w3c.github.io/picture-in-picture/#disable-pip
https://w3c.github.io/picture-in-picture/#feature-policy

It looks like your issue comes from an extension POV. Let's discuss at https://github.com/GoogleChromeLabs/picture-in-picture-chrome-extension/issues/49
